# Generated by Django 5.0.2 on 2025-06-29 06:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_image_path', models.CharField(max_length=255)),
                ('new_image_path', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField()),
                ('verification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('embedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='verification.faceembedding')),
            ],
        ),
    ]
